### ISSUE TITLE
Repository - yaml export corrupted under "httpclient" when there is no "connection" attributes

### ISSUE THREAD

**Issue by brenuart** [brenuart/nexus-casc-plugin#7]
Export of a Mean-Proxy repository without any special "Http Client" configuration looks like this:
```
attrs:
  httpclient:
    connection:
      blocked: true
      autoBlock: true
```

They `blocked` and `autoBlock` attributes appear as member of the `connection` node whereas they belong to the `httpclient` and should be exported as follows:
```
attrs:
  httpclient:
    blocked: true
    autoBlock: true
    connection:
      userAgentSuffix: custom
      retries: null
      ...
```
