### ISSUE TITLE
Repository - cannot create/update a Group repository with no members

### ISSUE THREAD

**Issue by brenuart** [brenuart/nexus-casc-plugin#8]
Creating a group repository with an empty list of members fails with a "group.memberNames cannot be null" error message.
Example:
```
  - name: maven
    recipeName: maven2-group
    online: true
    attrs:
      group:
        memberNames:
      maven:
        contentDisposition: INLINE
        versionPolicy: MIXED
        layoutPolicy: STRICT
```

This is probably caused by the YAML deserialisation that doesn't know the `memberNames` is a collection (there is no schema) and assigns a `null` value instead of an empty collection.
